services:
  icecast:
    build: ./icecast
    container_name: icecast
    ports:
      - "8000:8000"

  liquidsoap:
    build: ./radio
    container_name: liquidsoap
    depends_on:
      - icecast

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "4000:80"
    depends_on:
      - icecast
