services:
  icecast:
    build: ./icecast
    container_name: icecast
    ports:
      - "8000:8000"

  liquidsoap:
    build: ./radio
    container_name: liquidsoap
    depends_on:
      - icecast
  # backend-api:
  #   build: ./backend-api
  #   container_name: backend-api
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - icecast
